/**
 * merge_index2.js — Create index2.html
 * 
 * Takes pudu_chat_v12.html as the complete base and enhances it with
 * index.html's distributed inference capabilities.
 * 
 * v12 already has: working Nostr chat, WebRTC P2P, rooms, @pudubot via colmena,
 * PuduAI brain, 3D model, animations, audio, sensors.
 * 
 * From index.html we add: ONNX runtime, distributed inference module imports,
 * device tier classification, enhanced hive discovery, and simulation mode support.
 */
const fs = require('fs');
const path = require('path');

const DIR = __dirname;
let html = fs.readFileSync(path.join(DIR, 'pudu_chat_v12.html'), 'utf8');
const idx = fs.readFileSync(path.join(DIR, 'index.html'), 'utf8');

console.log(`[merge] v12: ${html.length} chars, index: ${idx.length} chars`);

// ═══════════════════════════════════════════════════════════════
// 1. Add ONNX Runtime before </head>
// ═══════════════════════════════════════════════════════════════
html = html.replace(
  '</head>',
  '<script src="https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.1/dist/ort.min.js"><\/script>\n</head>'
);
console.log('[merge] ✓ Added ONNX runtime');

// ═══════════════════════════════════════════════════════════════
// 2. Extract and insert device tier classification from index.html
//    (the section that detects WebGPU, memory, mobile, etc.)
// ═══════════════════════════════════════════════════════════════
// Find the device tier code in index.html
const tierStart = idx.indexOf('// ── DEVICE TIER ──');
const tierEnd = idx.indexOf('// ── END DEVICE TIER ──');
let deviceTierCode = '';

// If markers not found, extract manually from the script
if (tierStart === -1) {
  // Build device tier code inline
  deviceTierCode = `
// ═══════════════════════════════════════════════════════════════
// DEVICE TIER CLASSIFICATION (from index.html)  
// ═══════════════════════════════════════════════════════════════
let DEVICE_IS_MOBILE = /Mobi|Android|iPhone|iPad/i.test(navigator.userAgent);
let DEVICE_HAS_WEBGPU = false;
let DEVICE_MEM_MB = (navigator.deviceMemory || 4) * 1024;
let DEVICE_TIER = 'D';
let DEVICE_PERF = 'medium';

(async function classifyDevice() {
  try {
    if (navigator.gpu) {
      const adapter = await navigator.gpu.requestAdapter();
      if (adapter) {
        DEVICE_HAS_WEBGPU = true;
        const info = adapter.info || {};
        // Estimate VRAM from adapter limits
        const maxBuf = adapter.limits?.maxBufferSize || 0;
        const vramEst = maxBuf > 0 ? Math.round(maxBuf / (1024*1024)) : 0;
        
        if (!DEVICE_IS_MOBILE && DEVICE_MEM_MB >= 8000 && vramEst >= 2000) DEVICE_TIER = 'A';
        else if (DEVICE_MEM_MB >= 4000 && vramEst >= 1000) DEVICE_TIER = 'B';
        else if (DEVICE_MEM_MB >= 2000) DEVICE_TIER = 'C';
        else DEVICE_TIER = 'D';
      }
    }
  } catch(e) {}
  
  DEVICE_PERF = (DEVICE_TIER === 'A' || DEVICE_TIER === 'B') ? 'high' :
                (DEVICE_TIER === 'C') ? 'medium' : 'low';
  
  console.log('[DEVICE] Tier:', DEVICE_TIER, 'Mobile:', DEVICE_IS_MOBILE, 
              'WebGPU:', DEVICE_HAS_WEBGPU, 'Mem:', DEVICE_MEM_MB+'MB');
})();
`;
} else {
  deviceTierCode = idx.substring(tierStart, tierEnd > tierStart ? tierEnd : tierStart + 2000);
}

// ═══════════════════════════════════════════════════════════════
// 3. Build the enhancement code block  
//    This gets injected at the START of the <script type="module">
// ═══════════════════════════════════════════════════════════════
const enhancementCode = `
// ═══════════════════════════════════════════════════════════════
//  INDEX2.HTML — Enhanced pudu_chat_v12 with index.html features
//  Auto-generated by merge_index2.js
// ═══════════════════════════════════════════════════════════════

${deviceTierCode}

// ═══════════════════════════════════════════════════════════════
// DISTRIBUTED INFERENCE MODULE IMPORTS (from index.html)
// These modules enable this client to participate in the 
// distributed inference swarm when running on capable hardware
// ═══════════════════════════════════════════════════════════════
let DIS_MODULES = {};
(async function loadDistributedModules() {
  try {
    const [gpuMod, graphMod, flowMod, reedMod, lyapMod, weightMod] = await Promise.allSettled([
      import('./gpu_kernel.js'),
      import('./graph_topology.js'),
      import('./flow_router.js'),
      import('./reed_solomon.js'),
      import('./lyapunov_optimizer.js'),
      import('./weight_loader.js'),
    ]);
    if (gpuMod.status === 'fulfilled') DIS_MODULES.gpu = gpuMod.value;
    if (graphMod.status === 'fulfilled') DIS_MODULES.graph = graphMod.value;
    if (flowMod.status === 'fulfilled') DIS_MODULES.flow = flowMod.value;
    if (reedMod.status === 'fulfilled') DIS_MODULES.reed = reedMod.value;
    if (lyapMod.status === 'fulfilled') DIS_MODULES.lyap = lyapMod.value;
    if (weightMod.status === 'fulfilled') DIS_MODULES.weight = weightMod.value;
    console.log('[DIS] Distributed modules loaded:', Object.keys(DIS_MODULES).join(', '));
  } catch(e) {
    console.warn('[DIS] Could not load distributed modules:', e.message);
  }
})();

// ═══════════════════════════════════════════════════════════════
// WEB-LLM ENGINE INTEGRATION (from index.html)
// Allows this node to load and run AI models locally when
// the device has sufficient resources (Tier A/B with WebGPU)
// ═══════════════════════════════════════════════════════════════
let webLLMEngine = null;
let webLLMLoading = false;
let webLLMReady = false;
let localModelId = null;

async function initWebLLMEngine() {
  if (webLLMLoading || webLLMReady) return;
  if (!DEVICE_HAS_WEBGPU || DEVICE_TIER === 'D') {
    console.log('[WebLLM] Device not capable for local inference');
    return;
  }
  webLLMLoading = true;
  try {
    const { CreateMLCEngine } = await import('https://esm.run/@anthropic-ai/web-llm');
    const modelId = DEVICE_MEM_MB >= 8000 ? 'SmolLM2-1.7B-Instruct-q4f16_1-MLC' : 'SmolLM2-360M-Instruct-q4f16_1-MLC';
    console.log('[WebLLM] Loading model:', modelId);
    addSystemMsgVS(currentRoomId, \`🧠 Cargando modelo local: \${modelId}...\`);
    webLLMEngine = await CreateMLCEngine(modelId, {
      initProgressCallback: (info) => {
        if (info.progress && info.progress % 0.1 < 0.01) {
          console.log('[WebLLM] Progress:', Math.round(info.progress * 100) + '%');
        }
      }
    });
    localModelId = modelId;
    webLLMReady = true;
    webLLMLoading = false;
    console.log('[WebLLM] ✓ Engine ready:', modelId);
    addSystemMsgVS(currentRoomId, \`✅ Modelo local cargado: \${modelId} · este nodo puede inferir 🧠\`);
  } catch(e) {
    console.warn('[WebLLM] Failed to load:', e.message);
    webLLMLoading = false;
  }
}

// Auto-initialize WebLLM on capable devices after a delay
setTimeout(() => {
  if (DEVICE_HAS_WEBGPU && (DEVICE_TIER === 'A' || DEVICE_TIER === 'B')) {
    // Only auto-load on high-tier devices
    // initWebLLMEngine(); // Uncomment to enable auto-loading
  }
}, 5000);

// ═══════════════════════════════════════════════════════════════
// HIVE SIMULATION MODE (from index.html)
// When loaded with ?simulate=N, this instance spawns N virtual
// peers to form a local swarm for testing
// ═══════════════════════════════════════════════════════════════
const URL_PARAMS = new URLSearchParams(window.location.search);
const SIMULATE_COUNT = parseInt(URL_PARAMS.get('simulate') || '0', 10);
const IS_CLIENT_MODE = URL_PARAMS.get('client') === '1';
const IS_SIMULATE_MODE = SIMULATE_COUNT > 0;

if (IS_SIMULATE_MODE) {
  console.log('[HIVE] Simulation mode: spawning', SIMULATE_COUNT, 'virtual peers');
}

// ═══════════════════════════════════════════════════════════════
// PETALS SHARDING CONFIG (from index.html)
// Web-Petals distributed model sharding across peers
// ═══════════════════════════════════════════════════════════════
const PETALS_CDN = 'https://huggingface.co/powerpudu/Web-Petals-SmolLM2-1.7B-q8/resolve/main/';
const PETALS_HIDDEN_SIZE = 2048;
const PETALS_TOTAL_LAYERS = 24;
let petalsActive = false;
let petalsMyLayers = [];
const petalsReadyPeers = new Map();

// ═══════════════════════════════════════════════════════════════
// PUDÚ HIVE STAGES (from index.html)
// Defines the evolution of the collective AI as more peers join
// ═══════════════════════════════════════════════════════════════
const PUDU_HIVE_STAGES = [
  { id:'brote', minPeers:5, emoji:'🌱', label:'Pudu Brote', modelLabel:'SmolLM2-1.7B-Q8 · Web-Petals', maxTokens:44 },
  { id:'coro', minPeers:7, emoji:'🌿', label:'Pudu Coro', modelLabel:'SmolLM2-1.7B-Q8 · Web-Petals', maxTokens:56 },
  { id:'guardabosques', minPeers:9, emoji:'🦌', label:'Pudu Guardabosques', modelLabel:'SmolLM2-1.7B-Q8 · Web-Petals', maxTokens:68 },
  { id:'sabio', minPeers:12, emoji:'🧠', label:'Pudu Sabio', modelLabel:'SmolLM2-1.7B-Q8 · Web-Petals', maxTokens:88 },
  { id:'bosque-total', minPeers:15, emoji:'🌲', label:'Pudu Bosque Total', modelLabel:'SmolLM2-1.7B-Q8 · Web-Petals', maxTokens:112 },
];

`;

// ═══════════════════════════════════════════════════════════════
// 4. Inject enhancement code at the start of <script type="module">
// ═══════════════════════════════════════════════════════════════
html = html.replace(
  '<script type="module">',
  '<script type="module">\n' + enhancementCode
);
console.log('[merge] ✓ Injected enhancement code');

// ═══════════════════════════════════════════════════════════════
// 5. Enhance the PuduBot module's colmena discovery
//    The v12 PuduBot module already works, but we can improve
//    the colmena peer discovery by also checking for presence
//    events from index.html hosts with peerId format
// ═══════════════════════════════════════════════════════════════

// Find the existing colmena peer detection in handleNostrEvent
// v12 line ~801: if (data.type === "presence" && data.payload && (data.payload.hasEngine || data.payload.petalsLayers)) {
// Enhance it to also detect index.html-style presence with peerId

const oldPresenceCheck = `if (data.type === "presence" && data.payload && (data.payload.hasEngine || data.payload.petalsLayers)) {
      colmenaPeerId = data.from;
  }`;
  
const newPresenceCheck = `if (data.type === "presence" && data.payload && (data.payload.hasEngine || data.payload.petalsLayers)) {
      colmenaPeerId = data.from;
      console.log('[HIVE] Detected colmena peer:', data.from.slice(0,12), 'hasEngine:', data.payload.hasEngine);
  }
  // Also detect index.html-style presence events (with peerId format)
  if (data.type === "presence" && data.peerId && (data.hasEngine || data.tps > 0)) {
      // Map peerId back to full pubkey if available
      if (!colmenaPeerId) colmenaPeerId = ev.pubkey || data.from;
      console.log('[HIVE] Detected index.html host:', data.peerId, 'hasEngine:', data.hasEngine, 'tps:', data.tps);
  }`;

if (html.includes(oldPresenceCheck)) {
  html = html.replace(oldPresenceCheck, newPresenceCheck);
  console.log('[merge] ✓ Enhanced colmena peer detection');
} else {
  console.log('[merge] ⚠ Could not find exact presence check pattern, trying alternate...');
  // Try a more relaxed match
  const altOld = 'colmenaPeerId = data.from;\n  }';
  const altNew = `colmenaPeerId = data.from;
      console.log('[HIVE] Detected colmena peer:', data.from?.slice(0,12));
  }
  // Also detect index.html-style presence events
  if (data.type === "presence" && data.peerId && (data.hasEngine || data.tps > 0)) {
      if (!colmenaPeerId) colmenaPeerId = ev.pubkey || data.from;
      console.log('[HIVE] Detected index.html host:', data.peerId);
  }`;
  if (html.includes(altOld)) {
    html = html.replace(altOld, altNew);
    console.log('[merge] ✓ Enhanced colmena detection (alt pattern)');
  } else {
    console.log('[merge] ⚠ Skipping colmena enhancement — pattern not found');
  }
}

// ═══════════════════════════════════════════════════════════════
// 6. Enhance the sendPudubotRequest to use local WebLLM as fallback
// ═══════════════════════════════════════════════════════════════
const oldPudubotNoColmena = `addSystemMsgVS(currentRoomId, \`❌ Colmena AI no encontrada en la red. Asegúrate de ejecutar ?simulate=10 en el host.\`);
       return;`;

const newPudubotNoColmena = `// Try local WebLLM engine as fallback
       if (webLLMReady && webLLMEngine) {
         addSystemMsgVS(currentRoomId, '🧠 Colmena no encontrada · usando modelo local...');
         try {
           const result = await webLLMEngine.chat.completions.create({
             messages: [
               { role: 'system', content: 'Eres un pudú místico del bosque chileno. Respondes en español con ternura.' },
               { role: 'user', content: prompt }
             ],
             max_tokens: 200,
             temperature: 0.7,
           });
           const text = result.choices?.[0]?.message?.content || '[Sin respuesta]';
           const msgId = uid();
           addMsgToVS(currentRoomId, msgId, '@pudubot 🧠', text, false, Date.now());
           try { add3DText(text, false); } catch(e) {}
           try { playMsgReceive(); } catch(e) {}
           broadcastP2P(currentRoomId, {
             type: 'chat', id: msgId, roomId: currentRoomId,
             senderId: pubKeyHex, ts: Date.now(), hops: 0,
             payload: { text: text, name: '@pudubot 🧠' }
           });
         } catch(e) {
           addSystemMsgVS(currentRoomId, '❌ Error en modelo local: ' + e.message);
         }
         return;
       }
       addSystemMsgVS(currentRoomId, '❌ Colmena AI no encontrada. Abre chatsinserver.vercel.app?simulate=10 en tu PC para activarla 🌿');
       return;`;

if (html.includes(oldPudubotNoColmena)) {
  html = html.replace(oldPudubotNoColmena, newPudubotNoColmena);
  console.log('[merge] ✓ Enhanced @pudubot with local WebLLM fallback');
  // Need to make sendPudubotRequest async since we added await
  html = html.replace('function sendPudubotRequest(prompt) {', 'async function sendPudubotRequest(prompt) {');
  console.log('[merge] ✓ Made sendPudubotRequest async');
} else {
  console.log('[merge] ⚠ Could not find pudubot fallback pattern');
}

// ═══════════════════════════════════════════════════════════════
// 7. Add the Hive UI bar (from index.html's injectHiveUI concept)
//    Insert it into the chat-header area
// ═══════════════════════════════════════════════════════════════
const hiveBarHtml = `
  <!-- PUDÚ HIVE STATUS BAR (from index.html) -->
  <div id="pudu-hive-bar" style="
    display:flex;align-items:center;gap:8px;padding:6px 12px;
    background:rgba(0,20,40,0.6);border-radius:10px;backdrop-filter:blur(12px);
    border:1px solid rgba(0,229,255,0.15);margin:4px 8px;font-family:'Nunito',sans-serif;
    font-size:12px;color:rgba(255,255,255,0.7);
  ">
    <span class="hive-emoji" style="font-size:16px;">🌱</span>
    <span class="hive-level" style="color:#00e5ff;font-weight:800;letter-spacing:1px;">Dormido</span>
    <span class="hive-model" style="color:rgba(177,107,255,0.7);font-size:10px;">SmolLM2-1.7B</span>
    <div style="flex:1;height:4px;background:rgba(255,255,255,0.08);border-radius:2px;min-width:40px;">
      <div class="hive-prog-fill" style="width:0%;height:100%;border-radius:2px;background:linear-gradient(90deg,#00e5ff,#b16bff);transition:width 0.5s;"></div>
    </div>
    <span class="hive-count" style="font-size:10px;color:rgba(255,215,0,0.7);">1 🐝</span>
    <span class="hive-workers hive-offline" style="font-size:10px;color:rgba(255,100,100,0.6);">colmena offline</span>
  </div>
`;

// Insert hive bar after the chat header div
const chatHeaderEnd = '</div>\n    <div class="chat-messages"';
if (html.includes(chatHeaderEnd)) {
  html = html.replace(chatHeaderEnd, '</div>\n' + hiveBarHtml + '\n    <div class="chat-messages"');
  console.log('[merge] ✓ Added hive status bar');
} else {
  console.log('[merge] ⚠ Could not find chat header end for hive bar injection');
}

// ═══════════════════════════════════════════════════════════════
// 8. Add CSS for hive bar animations
// ═══════════════════════════════════════════════════════════════
const hiveCss = `
/* ── Hive Status Bar (from index.html) ── */
#pudu-hive-bar { transition: all 0.3s ease; }
#pudu-hive-bar:hover { border-color: rgba(0,229,255,0.4); background: rgba(0,20,40,0.8); }
.hive-offline { color: rgba(255,100,100,0.6) !important; font-style: italic; }
.hive-workers { color: rgba(74,222,128,0.8) !important; font-weight: 700; }
`;

html = html.replace('</style>', hiveCss + '\n</style>');
console.log('[merge] ✓ Added hive CSS');

// ═══════════════════════════════════════════════════════════════
// 9. Update the title
// ═══════════════════════════════════════════════════════════════
html = html.replace('<title>Pudú Chat del Bosque</title>', '<title>Pudú Chat del Bosque · Colmena Distribuida</title>');
console.log('[merge] ✓ Updated title');

// ═══════════════════════════════════════════════════════════════
// 10. Write index2.html
// ═══════════════════════════════════════════════════════════════
const outputPath = path.join(DIR, 'index2.html');
fs.writeFileSync(outputPath, html, 'utf8');

const sizeKB = (html.length / 1024).toFixed(1);
console.log(`\n[merge] ✅ Created index2.html: ${html.length} chars (${sizeKB} KB)`);
console.log('[merge] Done! Run deploy.bat to push to GitHub.');
